### ISSUE TITLE
[ENHANCEMENT]: Always heating mode after sterilization

### ISSUE THREAD

**Issue by omenukas** [edterbak/NodeRed_Heishamon_control#108]
The water sterilization time is set in the pump itself. I noticed that after sterilization, the pump always switches to heating mode, regardless of the mode it was in before sterilization.
Is it possible to solve this problem so that after water sterilization the pump returns to the mode it was in before sterilization? After all, there is no need to turn on the heating in the summer.
Are some changes needed in the NR dashboard or is this a bug?

**Comment by edterbak** [comment]
I think it is a bug. 
It might be fixed in current version (JUST pushed out) beta v22.27

https://github.com/edterbak/NodeRed_Heishamon_control/tree/beta-1

**Comment by omenukas** [comment]
> I think it is a bug. It might be fixed in current version (JUST pushed out) beta v22.27
> 
> https://github.com/edterbak/NodeRed_Heishamon_control/tree/beta-1
> 
> If you can check this version and pay special attention to this, that would be awesome :)
> 
> THanks for the reporting !!

I did the flows update as described in the instructions and set test sterilization on the pump. However, after sterilization, the pump still switched to heating mode.
Is it possible that I have incorrectly added the room temperature sensor and it is affecting the incorrect operation of the pump after sterilization?
I didn't make any more changes.
![Screenshot_20230509_152158_Home Assistant](https://github.com/edterbak/NodeRed_Heishamon_control/assets/122688908/af3c1c8d-0f75-4913-bc8c-e2bd63d41bf8)

**Comment by edterbak** [comment]
Ah, Im looking now at the code. 
it is not a bug. 
It is just not programmed as you and I thought it was. 
I will have a look if it is doable to change. (it is complex in interaction with other functions... need to see...)

**Comment by edterbak** [comment]
I think I fixed it on my end. Did a testrun, and it worked. ofcourse the proof is in the pudding, so after upload/release the bughunting can start.

**Comment by omenukas** [comment]
Can I try it or do I have to wait for a new release?

**Comment by edterbak** [comment]
It is in current upload, v22.28

**Comment by omenukas** [comment]
I tried force sterilization. The problem remained the same - after sterilization, the pump switched to heating mode.
Before sterilization, "only DHW" mode was activated.

**Comment by edterbak** [comment]
Maybe we are talking about two different things.
How do you enabling the sterilisation ?
Through the scheduler or home dashboard?

**Comment by omenukas** [comment]
Sterilisation is normally set on the heat pump's dashboard. This time I enabled the "force sterilisation" function in the app for testing.
![Screenshot_20230510_203144_Home Assistant](https://github.com/edterbak/NodeRed_Heishamon_control/assets/122688908/e1e247ff-8299-4abf-a010-98377e0bed87)

**Comment by omenukas** [comment]
Yesterday I set up the "scheduler" function in the app:

![Screenshot_20230511_063437_Home Assistant](https://github.com/edterbak/NodeRed_Heishamon_control/assets/122688908/7d0a1994-78a9-4219-b565-8021071d239b)

This is what I found this morning:

![Screenshot_20230511_063233_Photos](https://github.com/edterbak/NodeRed_Heishamon_control/assets/122688908/c392ed7d-5b1d-4eb9-bc65-55172ae3a8b6)

**Comment by edterbak** [comment]
Are there schedules in the controler still active with heat only? 
Can you post a screenshot of the RTC page?
Are you sure the operating mode was different befor the schedule?

**Comment by edterbak** [comment]
Did i correctly see you use not direct mode but compensation curve?

**Comment by omenukas** [comment]
It's been a few weeks since I've had the heating off and only the water heating on. That's why I raised this issue only now. In winter, when both heating and water preparation were turned on, switching to "only heating" after sterilisation did not cause any problems, but now the situation is not very good.
Yes, the pump is set to work according to the compensation curve.
I don't put any shedule settings in the pump or the app. Yesterday, just for testing, I set the sterilisation schedule in the app.
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/122688908/5c505441-5fac-4374-b3de-092c3fd69836)
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/122688908/9bb57d73-ec01-482a-80d0-6f44fd57258c)

**Comment by edterbak** [comment]
Could you check if you have a value here:
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/f3552bd9-a736-4803-80b0-c717b2815218)

and a little further down you could see "F_stored_next_operating_mode"
![image](https://github.com/edterbak/NodeRed_Heishamon_control/assets/3155621/069bf304-9038-4f5d-9ffa-7a49c9667212)

Normally, this variable should not be found. 
Only during sterilization run, I expect this variable to contain the operating mode that was active befor the sterilization. 

So if you cnt find it, it is good. (when not in a sterilization run)

**Comment by edterbak** [comment]
Aaaahh.. okay. I have just found the cause.
Working on it.

**Comment by edterbak** [comment]
Found it

**Comment by albertoanta** [comment]
As you mention F_stored_next_operating_mode is empty, now i remember two weeks ago scheduled `Force DHW` in nodered dashboard, DHW was done but  when it finished it active heat mode. Suspect the same behavior  "it sends out the value 0 (zero) which is Heat Only".  
![Captura de pantalla de 2023-05-11 16-59-51](https://github.com/edterbak/NodeRed_Heishamon_control/assets/26067025/fc1a00c8-1a02-4847-b7ff-2bbf8e82db80)
The first blue area is when DHW force scheduled cycle, the second purple area is compressor runnig in Heat mode, when DHW force finished and previous state (DHW_only) was not restore. Compressor running is drawed in purple. I noticed why is on heating mode where it was at DHW_only mode.

**Comment by edterbak** [comment]
Ok. Let me digest this ..

The toggle on home screen is different than the schedular function. The toggle does not set F_stored_next_operating_mode. 
Ill make it similar soon.

**Comment by edterbak** [comment]
I have rewritten the Sterilization code part now.

The toggle on the dashboard is the same as doing a scheduled sterilization. 
I have tested it 3x now.

Toggle on: Heat only >> HEAT+DHW, + Sterelization = 1
Toggle on: HEAT+DHW >> Heat only, + Sterelization = 0

Toggle on: Auto(2)  >> Auto+DHW(6), + Sterelization = 1
Toggle on: Auto+DHW(6) >> Auto(2), + Sterelization = 0

It should be ok now. 
I will upload a version, version 22.29, in a minute

**Comment by omenukas** [comment]
Good news!! After installing version 22.29, the pump returned to DHW mode after force sterilization.
Now I will wait until Monday, when the regular sterilization will be done.
Weekly sterilization is set on the pump dashboard. Should it work with this setting or do I need to set the scheduler in the app?

**Comment by edterbak** [comment]
Good news indeed. Thanks.
If you only use the nr schedular, that is sufficient. You do not need the schedules steril task on the wall controller

**Comment by edterbak** [comment]
supurb. thanks for confirming !! :D

**Comment by omenukas** [comment]
> supurb. thanks for confirming !! :D

Hello again,
Could you please help in one more place?
I wanted to make an automation in node-red so that towards the evening, while the sun is still shining and the solar power plant is still producing electricity, the heat pump will heat the water.
The script activates "Force DHW" in the heat pump, but returns to "Heating only" when finished.
The solar power plant works independently, it is not connected to the heat pump and only the script controls the pump according to the sensor of the solar power plant.
Maybe this place can be fixed to return to the previous mode after Force DHW?

**Comment by edterbak** [comment]
Hi, 
Could you close this issue and make a new one?
the issue is solved here. It was about sterilization mode, and not force dhw. 

In the new thread/issue, I do like to have more info on your scenario.
How are you triggering exactly the force dhw. in detail. 
What script, what does it do. 
What is the state befor the script fires.
etc..
You can share the node (select + export) or use screenshots as well to make it clear what you are doing. 

Regards.
