### ISSUE TITLE
Input solarpower for the Solar²DHW function

### ISSUE THREAD

**Issue by plutoarko** [edterbak/NodeRed_Heishamon_control#170]
Please, where can I find the input for the current solar power for the Solar²DHW function?
In which tab ?
What is the name of the node? 

Thank you very much
Ulrich Springfeld

**Comment by edterbak** [comment]
Hi, sorry for the late reply

Can you tell me if you have the P1 meter information comming in Node Red?
If so, you need to connect it in the tab WP Input: 

![image](https://github.com/user-attachments/assets/a215e4f3-ea92-4f51-b970-a2f0f46ac459)

When you have done this... very logicly (NOT!!) you need to go in the System > Sensor tab
Next you need to reset the sensor by clicking one the trashcan for both P1's once. 
After that you need to wait until the first readings come in. 
When the readings come in, y ou can select the correct topic / value in the dropdown on the left side.

Also, you need to check the tab: Solar2DHW > P1 Setup.
when sensor values come it, it can be that the values are not correct, like 1000x to large or small. You can correct it here. 

It is not all that intuitive. It is the result of incremental development. But it should work in the end.

I am moving things arouund to make it easier.

**Comment by plutoarko** [comment]
Hi ,
It was a quick answer, thank you.I have brought the output from the power measurement to the WP input tab. I'm sure you can see it.  But I can't connect it to P1 power production. That doesn't work somehow. There is a linkout_83 connection. Do I have to remove the link first? Lots of questions...
Nevertheless, thank you very much for your great work.

    Am Samstag, 21. September 2024 um 23:13:47 MESZ hat Ed ter Bak ***@***.***> Folgendes geschrieben:   

 


Hi, sorry for the late reply

Can you tell me if you have the P1 meter information comming in Node Red?
If so, you need to connect it in the tab WP Input:

image.png (view on web)

When you have done this... very logicly (NOT!!) you need to go in the System > Sensor tab
Next you need to reset the sensor by clicking one the trashcan for both P1's once.
After that you need to wait until the first readings come in.
When the readings come in, y ou can select the correct topic / value in the dropdown on the left side.

Also, you need to check the tab: Solar2DHW > P1 Setup.
when sensor values come it, it can be that the values are not correct, like 1000x to large or small. You can correct it here.

It is not all that intuitive. It is the result of incremental development. But it should work in the end.

I am moving things arouund to make it easier.

**Comment by edterbak** [comment]
can you put a debug node after your P1 sensor input? I want to see the data type which it is producing.
I would like to see the output of the debug node.

**Comment by plutoarko** [comment]
The following message comes from my P-sensor: 
 "Time": "2024-09-22T18:09:43", " ": { "vom_Netz": 5415.622,  "zum_netz": 3095.9442, "mom_Leistung": 107 }}

using the following function ("Netzleistung") 

1 var msg1 = { payload: msg.payload[" "].mom_Leistung};2 return msg1 ;
I get the numerical Result  107 (in this case)


I am very happy about your help, but please - there is no hurry.
        can you put a debug node after your P1 sensor input? I want to see the data type which it is producing.
I would like to see the output of the debug node.

**Comment by edterbak** [comment]
This part is kind of 'funny'
 >"Time": "2024-09-22T18:09:43", " ": { "vom_Netz": 5415.622,  "zum_netz": 3095.9442, "mom_Leistung": 107 }}
the ," ": part seems to be breaking all logic.
if I replace the space between the quotes by something random, eg "test", then object gets a name and the values can be extracted. 

The below code works when I replace the space with 'test'. 
```
[
    {
        "id": "9c1c469724a8c470",
        "type": "inject",
        "z": "d5fea67661261002",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1400,
        "y": 640,
        "wires": [
            [
                "8c0cb8a7de042ee3"
            ]
        ]
    },
    {
        "id": "8c0cb8a7de042ee3",
        "type": "function",
        "z": "d5fea67661261002",
        "name": "incoming message generation",
        "func": "var msg1={}\n//msg1={\"Time\": \"2024-09-22T18:09:43\", \" \": { \"vom_Netz\": 5415.622,  \"zum_netz\": 3095.9442, \"mom_Leistung\": 107 }}\nmsg1={\"Time\": \"2024-09-22T18:09:43\", \"test\": { \"vom_Netz\": 5415.622,  \"zum_netz\": 3095.9442, \"mom_Leistung\": 107 }}\nreturn msg1;\n",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1630,
        "y": 640,
        "wires": [
            [
                "ca750540b7cb875b",
                "fb158560eb14e8e4"
            ]
        ]
    },
    {
        "id": "ca750540b7cb875b",
        "type": "debug",
        "z": "d5fea67661261002",
        "name": "debug 338",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1870,
        "y": 580,
        "wires": []
    },
    {
        "id": "fb158560eb14e8e4",
        "type": "function",
        "z": "d5fea67661261002",
        "name": "function 108",
        "func": "var msg1={};\nvar msg2={};\n\nmsg1.payload = msg.test.vom_Netz;\nmsg2.payload = msg.test.zum_netz;\n\nreturn [msg1,msg2];\n",
        "outputs": 2,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1930,
        "y": 640,
        "wires": [
            [
                "a4cdcc9d04e043ce"
            ],
            [
                "245119d620efab47"
            ]
        ],
        "outputLabels": [
            "vom_Netz",
            "zum_netz"
        ]
    },
    {
        "id": "a4cdcc9d04e043ce",
        "type": "debug",
        "z": "d5fea67661261002",
        "name": "debug 339",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 2170,
        "y": 600,
        "wires": []
    },
    {
        "id": "245119d620efab47",
        "type": "debug",
        "z": "d5fea67661261002",
        "name": "debug 340",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 2170,
        "y": 680,
        "wires": []
    }
]
```

When changing back the 'test' value to the empty space " ", the same code fails. 

If you can get your P sensor to produce the measurement in a proper format, I think that would help

**Comment by plutoarko** [comment]
First of all, thank you very much. I have to understand this first, but that may take a while. I will then get back to you here.



 

    Am Sonntag, 29. September 2024 um 18:15:16 MESZ hat Ed ter Bak ***@***.***> Folgendes geschrieben:   

 


This part is kind of 'funny'


"Time": "2024-09-22T18:09:43", " ": { "vom_Netz": 5415.622, "zum_netz": 3095.9442, "mom_Leistung": 107 }}
the ," ": part seems to be breaking all logic.
if I replace the space between the quotes by something random, eg "test", then object gets a name and the values can be extracted.


The below code works when I replace the space with 'test'.
[
    {
        "id": "9c1c469724a8c470",
        "type": "inject",
        "z": "d5fea67661261002",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1400,
        "y": 640,
        "wires": [
            [
                "8c0cb8a7de042ee3"
            ]
        ]
    },
    {
        "id": "8c0cb8a7de042ee3",
        "type": "function",
        "z": "d5fea67661261002",
        "name": "incoming message generation",
        "func": "var msg1={}\n//msg1={\"Time\": \"2024-09-22T18:09:43\", \" \": { \"vom_Netz\": 5415.622,  \"zum_netz\": 3095.9442, \"mom_Leistung\": 107 }}\nmsg1={\"Time\": \"2024-09-22T18:09:43\", \"test\": { \"vom_Netz\": 5415.622,  \"zum_netz\": 3095.9442, \"mom_Leistung\": 107 }}\nreturn msg1;\n",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1630,
        "y": 640,
        "wires": [
            [
                "ca750540b7cb875b",
                "fb158560eb14e8e4"
            ]
        ]
    },
    {
        "id": "ca750540b7cb875b",
        "type": "debug",
        "z": "d5fea67661261002",
        "name": "debug 338",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1870,
        "y": 580,
        "wires": []
    },
    {
        "id": "fb158560eb14e8e4",
        "type": "function",
        "z": "d5fea67661261002",
        "name": "function 108",
        "func": "var msg1={};\nvar msg2={};\n\nmsg1.payload = msg.test.vom_Netz;\nmsg2.payload = msg.test.zum_netz;\n\nreturn [msg1,msg2];\n",
        "outputs": 2,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1930,
        "y": 640,
        "wires": [
            [
                "a4cdcc9d04e043ce"
            ],
            [
                "245119d620efab47"
            ]
        ],
        "outputLabels": [
            "vom_Netz",
            "zum_netz"
        ]
    },
    {
        "id": "a4cdcc9d04e043ce",
        "type": "debug",
        "z": "d5fea67661261002",
        "name": "debug 339",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 2170,
        "y": 600,
        "wires": []
    },
    {
        "id": "245119d620efab47",
        "type": "debug",
        "z": "d5fea67661261002",
        "name": "debug 340",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 2170,
        "y": 680,
        "wires": []
    }
]

When changing back the 'test' value to the empty space " ", the same code fails.

If you can get your P sensor to produce the measurement in a proper format, I think that would help

**Comment by plutoarko** [comment]
Now I have recorded everything again in a similar way like you did, maybe there was a copying error before.  It always works as desired for me. 

 



// Output of Node ‚mqtt in‘ via node debug 267//







9.9.2024, 20:02:31 node: debug 267

tele/Keller/Energiezaehler/SENSOR: msg : Object

{"topic":"tele/Keller/Energiezaehler/SENSOR","payload":{"Time":"2024-09-29T19:02:31","":{"vom_Netz":5460.6932,"zum_netz":3116.5713,"mom_Leistung":180.79}},"qos":0,"retain":false,"_msgid":"3c4b61b5e4104f76"}

// my Funktion „Netzleistung“ //
[
    {
        "id": "5af365858e8c2012",
        "type": "function",
        "z": "ad980a450f532e53",
        "name": "Netzleistung",
        "func": "var msg1 = { payload: msg.payload[\" \"].mom_Leistung};\nreturn msg1 ;",
        "outputs": 1,
        "timeout": "",
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 130,
        "y": 2300,
        "wires": [
            [
                "cbba9a4ba57fde3b"
            ]
        ]
    }
]

// Output of Funktion ‚Netzleistung‘ via Node debug 266 //

29.9.2024, 20:02:31 node:debug 266

msg : Object
{"payload":180.79,"_msgid":"3c4b61b5e4104f76"}

// 180.79 //







    Am Sonntag, 29. September 2024 um 18:15:16 MESZ hat Ed ter Bak ***@***.***> Folgendes geschrieben:   

 


This part is kind of 'funny'


"Time": "2024-09-22T18:09:43", " ": { "vom_Netz": 5415.622, "zum_netz": 3095.9442, "mom_Leistung": 107 }}
the ," ": part seems to be breaking all logic.
if I replace the space between the quotes by something random, eg "test", then object gets a name and the values can be extracted.


The below code works when I replace the space with 'test'.
[
    {
        "id": "9c1c469724a8c470",
        "type": "inject",
        "z": "d5fea67661261002",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 1400,
        "y": 640,
        "wires": [
            [
                "8c0cb8a7de042ee3"
            ]
        ]
    },
    {
        "id": "8c0cb8a7de042ee3",
        "type": "function",
        "z": "d5fea67661261002",
        "name": "incoming message generation",
        "func": "var msg1={}\n//msg1={\"Time\": \"2024-09-22T18:09:43\", \" \": { \"vom_Netz\": 5415.622,  \"zum_netz\": 3095.9442, \"mom_Leistung\": 107 }}\nmsg1={\"Time\": \"2024-09-22T18:09:43\", \"test\": { \"vom_Netz\": 5415.622,  \"zum_netz\": 3095.9442, \"mom_Leistung\": 107 }}\nreturn msg1;\n",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1630,
        "y": 640,
        "wires": [
            [
                "ca750540b7cb875b",
                "fb158560eb14e8e4"
            ]
        ]
    },
    {
        "id": "ca750540b7cb875b",
        "type": "debug",
        "z": "d5fea67661261002",
        "name": "debug 338",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1870,
        "y": 580,
        "wires": []
    },
    {
        "id": "fb158560eb14e8e4",
        "type": "function",
        "z": "d5fea67661261002",
        "name": "function 108",
        "func": "var msg1={};\nvar msg2={};\n\nmsg1.payload = msg.test.vom_Netz;\nmsg2.payload = msg.test.zum_netz;\n\nreturn [msg1,msg2];\n",
        "outputs": 2,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1930,
        "y": 640,
        "wires": [
            [
                "a4cdcc9d04e043ce"
            ],
            [
                "245119d620efab47"
            ]
        ],
        "outputLabels": [
            "vom_Netz",
            "zum_netz"
        ]
    },
    {
        "id": "a4cdcc9d04e043ce",
        "type": "debug",
        "z": "d5fea67661261002",
        "name": "debug 339",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 2170,
        "y": 600,
        "wires": []
    },
    {
        "id": "245119d620efab47",
        "type": "debug",
        "z": "d5fea67661261002",
        "name": "debug 340",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "statusVal": "",
        "statusType": "auto",
        "x": 2170,
        "y": 680,
        "wires": []
    }
]

When changing back the 'test' value to the empty space " ", the same code fails.

If you can get your P sensor to produce the measurement in a proper format, I think that would help

**Comment by edterbak** [comment]
So the issue is now resolved?

**Comment by plutoarko** [comment]
No, not yet. I'm still thinking about it. But there's no rush at the moment.

    Am Mittwoch, 2. Oktober 2024 um 01:02:08 MESZ hat Ed ter Bak ***@***.***> Folgendes geschrieben:   

 


So the issue is now resolved?

**Comment by emilic14** [comment]
Quick question... just to make sure I am inputting the correct values.

Power production = Produced power by my solar panels
Power consumption = is it
1) the power being used by my house hold? (without taking into consideration the power production; its always a positive number)
2) the total power from my house hold (power being used + power produced; it can be negative when production is high)

Thank you for the clarification :)

**Comment by emilic14** [comment]
Thanks for the reply.
I just searched the [P1 power meter](https://www.homewizard.com/p1-meter/), I did not know they existed... and I am not sure its compatible with my energy meter :(

That said, I do have
a) solar panel information, that tells me what I produce. And also tells me what my house hold consumes with data every 5 min.
b) consumption information in real time that also tells me what am I producing, what I am consuming, and my output or input to the network.

So just to be clear, in the HW for scenario 1...
1.- Power production is what my solar panel produce. We are OK here.
2.- Power consumption is what my house imports from the grid. But does it takes into consideration the power I produce ? 

In my current power analysis of my consumption, I always know what my household is consuming even if I am producing more than I consume. 
Meaning that I can be producing 3kw, consuming 2kw and hence returning to the grid 1kw... So in this case of the HW scenario: Power production =3kw; 
is Power consumption 2kw? or is it -1kw(meaning I am exporting)? or should it be 0kw (as I am not importing anything)

That said, I want to use threshold option 1 as I want the DHW to work when I am producing more than I use, so I just need my solar production. 
But I would like to fully understand and know what is expected on the HW scenario 1. It may help me if I later change my mind and want to try the other scenarios.

**Comment by emilic14** [comment]
Thank you!
In my case I use clamps to read the energy used, one for the entry of the power and one for the panel generation. So it is exactly your IN or OUT values.

It is now way clear and I've set it up and seems to be working.
I'll just play a bit with the different options and I'll try to understand why would we want to use the different thresholds you propose.

**Comment by emilic14** [comment]
Well It seems that I did not get it...

After a few hours of usage, my power consumption meter can be negative when I am producing too much energy and sending the energy back to the grid. In the dashboard this consumption is always treated as Positive, so it thinks that I am consuming a LOT of energy when in fact i am not...

So I guess my Power consumption is still not exactly what the P1 meter provides and the system expects...

**Comment by edterbak** [comment]
Yes, exactly.

If you dont have it already, Create ons new tab called WP personal.
In there you fetch the source signal.
Int there you split the signal into 2 as you said.
From there you "link-out" to the "link-in" nodes 8n the WP input tab.

This way, you can install updates of the flow Easy without loosing your WP personal tab and this work. It will just continue to work as before
